### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.5

### PR DESCRIPTION
**Pull request by rvalieris**

### CODE REVIEW

**Comment by jdblischak** [comment]
@rvalieris Let's hold this one up. The dependency chain is

properties -> types -> strings

We updated types in https://github.com/conda-forge/r-assertive.types-feedstock/pull/1 before updating properties in https://github.com/conda-forge/r-assertive.properties-feedstock/pull/1. Thus types is still missing the win-64 build for 3.4.1, and strings in this PR as well.

We need the win-64 build for R 3.4.1 properties to finish building:

https://ci.appveyor.com/project/conda-forge/r-assertive-properties-feedstock/build/1.0.4/job/97avputp0qdc74pe

Then we can rerender types and then update this PR. Are you in a rush to get these all built for a specific architecture or is it ok if we comprehensively update them all?

**Comment by rvalieris** [comment]
ah, forgot to check windows builds on this one, sorry.

there is no rush at all, its better to wait for sure.

**Comment by jdblischak** [comment]
@rvalieris See https://github.com/conda-forge/r-assertive.types-feedstock/pull/2 which will build the package for win-64 for R 3.4.1.

Once it's merged, you can use the "please rerender" trick to update this PR https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
